# -*- coding: utf-8 -*-
"""analisis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bSJV_yNJw_uwQqVWF5XP6p_AvSZMVw9Z
"""

import pandas as pd
import numpy as np

def medidas_tendencia_central(df, columna):
    return {
        "media": df[columna].mean(),
        "mediana": df[columna].median(),
        "moda": df[columna].mode().iloc[0] if not df[columna].mode().empty else np.nan
    }


def medidas_dispersion(df, columna):
    return {
        "varianza": df[columna].var(),
        "desviacion_estandar": df[columna].std(),
        "rango": df[columna].max() - df[columna].min()
    }


def tabla_frecuencias(df, columna):
    return df[columna].value_counts().to_frame(name="frecuencia")


def porcentajes(df, columna):
    return df[columna].value_counts(normalize=True) * 100


def correlaciones(df):
    return df.select_dtypes(include=[np.number]).corr()